// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClyR-p1MQAQef7bH4lNsiSMpLfse9u3Mo',
    appId: '1:819516809721:web:06edc920d6fff7f9825d28',
    messagingSenderId: '819516809721',
    projectId: 'iconventory-web',
    authDomain: 'iconventory-web.firebaseapp.com',
    storageBucket: 'iconventory-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD78zA5jE_Ep_1zQKLe6FFURX7uS9aIrXw',
    appId: '1:819516809721:android:5741812312b695fa825d28',
    messagingSenderId: '819516809721',
    projectId: 'iconventory-web',
    storageBucket: 'iconventory-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIOP9mJmo2s5oXmZcx12xbz1TXAcbvCGo',
    appId: '1:819516809721:ios:954ea2d2a36f9b98825d28',
    messagingSenderId: '819516809721',
    projectId: 'iconventory-web',
    storageBucket: 'iconventory-web.appspot.com',
    iosBundleId: 'com.example.iconventoryWeb',
  );
}
